spring.application.name=citaria_backend

# Base de datos
spring.datasource.url=jdbc:mariadb://localhost:3306/citaria?useUnicode=true&characterEncoding=UTF-8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA / Hibernate
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT ? el secreto se lee de la variable de entorno JWT_SECRET
jwt.secret=${JWT_SECRET}

# Gemini API
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent