name: citaria_frontend
description: "Aplicación de gestión de citas para negocios de servicios."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.0
  shared_preferences: ^2.3.0
  flutter_secure_storage: ^9.0.0
  google_fonts: ^6.2.0
  fl_chart: ^0.68.0
  http: ^1.2.0
  intl: ^0.19.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^6.0.0
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo_citaria_r.png"
  remove_alpha_ios: true
